openapi: 3.0.0
info:
  title: Laravel API Starter
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
  - name: User
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@gmail.com
                password: '123456'
      security:
        - noauthAuth: []
      parameters:
        - name: apiKey
          in: header
          schema:
            type: string
          example: >-
            eyJ4NXQiOiJPREUzWTJaaE1UQmpNRE00WlRCbU1qQXlZemxpWVRJMllqUmhZVFpsT0dJeVptVXhOV0UzWVE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IjEwUGVyTWluIiwibmFtZSI6IkhlbGxvIFdvcmxkIiwiaWQiOjIsInV1aWQiOiI2OTE0ZjdiNy1mYjc1LTRkOWQtYjczNC0xODVmMjJjZTMxMzMifSwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiQnJvbnplIjp7InRpZXJRdW90YVR5cGUiOiJyZXF1ZXN0Q291bnQiLCJncmFwaFFMTWF4Q29tcGxleGl0eSI6MCwiZ3JhcGhRTE1heERlcHRoIjowLCJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJwZXJtaXR0ZWRSZWZlcmVyIjoiIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiUHJvbWV0ZXVzQWNjb3VudGluZ0FQSSIsImNvbnRleHQiOiJcL3Byb21ldGV1c2FjY291bnRpbmdhcGlcLzEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMS4wLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiQnJvbnplIn1dLCJ0b2tlbl90eXBlIjoiYXBpS2V5IiwicGVybWl0dGVkSVAiOiIiLCJpYXQiOjE2OTMwNTYyMjQsImp0aSI6IjJmNzVhZWMyLTZlYzItNGQ5ZS1hOWM2LTY1NTk4MjFmY2EyNSJ9.kUP5xZUzZak6Ywu5NfikkzWt8w8dBCadZclCy5qjJOJfd89gcTnOTrUa8VVIQsIiPi0rZNu9DQqbC_S0Dfvz75hrHdFVGcdMiB5CfsA2XU6kit9BJPmhjblD9B_cHj7ccrtDTSps9R--0zBT2tyj0xjQ-zT4hSQmZNzQ4kt0L3rOp19xHTvc2Vq6FjQtcdmnUTPFrDi7YouElBa4UacwI1Eg0lb4EVgYFn_JC4KTFp0yGWze9ztTfqykfKtI-iD6ebjII7pekGKg5dyXo6s7yIOiCF5aV-z_ji_g1FaKQkxJ33uTIrCH7J6atm8FA8eootVBDOyXdQsEDHLlFJ6lNw==
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:42:24 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '59'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  access_token: >-
                    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE2OTI5NzA5NDQsImV4cCI6MTY5Mjk3NDU0NCwibmJmIjoxNjkyOTcwOTQ0LCJqdGkiOiJzd1NtVU85MjA0QW5yZHhLIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.hCaYZ5SOduBcWaNJBcnPCtKHJzpZYSLlfKeFVxDq_RE
                  refresh_token: >-
                    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE2OTI5NzA5NDQsImV4cCI6MTY5Mjk3NDU0NCwibmJmIjoxNjkyOTcwOTQ0LCJqdGkiOiJJMTVPVGd0Y3lYNGpSb0phIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.2ENhczsJpZxwhU7s46PhlhwkPut_yMZyc8K9fxgQhjw
                  token_type: bearer
        '400':
          description: Bad Request
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:48:57 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '59'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Invalid credentials, please try again.
                status: error
                code: 400
                data: null
  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Refresh token
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:47:03 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '59'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  access_token: >-
                    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvcmVmcmVzaCIsImlhdCI6MTY5Mjk3MDk2MiwiZXhwIjoxNjkyOTc0ODIzLCJuYmYiOjE2OTI5NzEyMjMsImp0aSI6IjdFcHU5YmJlU29NRFJMREoiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.XYMvLfZjHTxgsfKkku0g6P0HlYlb7ycAN2xmKxCoU0k
                  refresh_token: >-
                    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvcmVmcmVzaCIsImlhdCI6MTY5Mjk3MDk2MiwiZXhwIjoxNjkyOTc0ODIzLCJuYmYiOjE2OTI5NzEyMjMsImp0aSI6IkcxdUdPTktEY3pHUm1HbUYiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.LjrUZdy0vOIDxjIEwM0KD1L6p1GdJv70vmVMVgkMepM
                  token_type: bearer
        '401':
          description: Unauthorized
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:53:24 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Unauthorized route, please login first
                status: error
                code: 401
                data: null
  /auth/me:
    post:
      tags:
        - Auth
      summary: Me
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@gmail.com
                password: '123456'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:47:14 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '57'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  id: 1
                  email: admin@gmail.com
                  first_name: Admin
                  last_name: User
                  email_verified_at: null
                  created_at: '2023-08-25T06:25:42.000000Z'
                  updated_at: '2023-08-25T06:25:42.000000Z'
        '401':
          description: Unauthorized
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:54:02 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Unauthorized route, please login first
                status: error
                code: 401
                data: null
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@gmail.com
                password: '123456'
      responses:
        '500':
          description: Internal Server Error
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:52:58 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '59'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: You must have the blacklist enabled to invalidate a token.
  /users:
    get:
      tags:
        - User
      summary: Get all
      parameters:
        - name: apiKey
          in: header
          schema:
            type: string
          example: >-
            eyJ4NXQiOiJPREUzWTJaaE1UQmpNRE00WlRCbU1qQXlZemxpWVRJMllqUmhZVFpsT0dJeVptVXhOV0UzWVE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IjEwUGVyTWluIiwibmFtZSI6IkhlbGxvIFdvcmxkIiwiaWQiOjIsInV1aWQiOiI2OTE0ZjdiNy1mYjc1LTRkOWQtYjczNC0xODVmMjJjZTMxMzMifSwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiQnJvbnplIjp7InRpZXJRdW90YVR5cGUiOiJyZXF1ZXN0Q291bnQiLCJncmFwaFFMTWF4Q29tcGxleGl0eSI6MCwiZ3JhcGhRTE1heERlcHRoIjowLCJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJwZXJtaXR0ZWRSZWZlcmVyIjoiIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiUHJvbWV0ZXVzQWNjb3VudGluZ0FQSSIsImNvbnRleHQiOiJcL3Byb21ldGV1c2FjY291bnRpbmdhcGlcLzEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMS4wLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiQnJvbnplIn1dLCJ0b2tlbl90eXBlIjoiYXBpS2V5IiwicGVybWl0dGVkSVAiOiIiLCJpYXQiOjE2OTMwNTYyMjQsImp0aSI6IjJmNzVhZWMyLTZlYzItNGQ5ZS1hOWM2LTY1NTk4MjFmY2EyNSJ9.kUP5xZUzZak6Ywu5NfikkzWt8w8dBCadZclCy5qjJOJfd89gcTnOTrUa8VVIQsIiPi0rZNu9DQqbC_S0Dfvz75hrHdFVGcdMiB5CfsA2XU6kit9BJPmhjblD9B_cHj7ccrtDTSps9R--0zBT2tyj0xjQ-zT4hSQmZNzQ4kt0L3rOp19xHTvc2Vq6FjQtcdmnUTPFrDi7YouElBa4UacwI1Eg0lb4EVgYFn_JC4KTFp0yGWze9ztTfqykfKtI-iD6ebjII7pekGKg5dyXo6s7yIOiCF5aV-z_ji_g1FaKQkxJ33uTIrCH7J6atm8FA8eootVBDOyXdQsEDHLlFJ6lNw==
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE2OTMwNTYzODAsImV4cCI6MTY5MzA1OTk4MCwibmJmIjoxNjkzMDU2MzgwLCJqdGkiOiJCUGdjTU90djB2UnlBcmF1Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.XGYu-_v5GCxgUqQodEr9ebZzMKhNxzlHjoQnb6lhq-M
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:47:45 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '55'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                current_page: 1
                data:
                  - id: 1
                    email: admin@gmail.com
                    first_name: Admin
                    last_name: User
                    email_verified_at: null
                    created_at: '2023-08-25T06:25:42.000000Z'
                    updated_at: '2023-08-25T06:25:42.000000Z'
                    roles:
                      - admin
                  - id: 2
                    email: user@gmail.com
                    first_name: User
                    last_name: User
                    email_verified_at: null
                    created_at: '2023-08-25T06:25:43.000000Z'
                    updated_at: '2023-08-25T06:25:43.000000Z'
                    roles:
                      - user
                  - id: 3
                    email: superadmin@gmail.com
                    first_name: Super
                    last_name: Admin
                    email_verified_at: null
                    created_at: '2023-08-25T06:25:43.000000Z'
                    updated_at: '2023-08-25T06:25:43.000000Z'
                    roles:
                      - super_admin
                  - id: 4
                    email: john.doe@example.com
                    first_name: John
                    last_name: Doe
                    email_verified_at: null
                    created_at: '2023-08-25T06:30:08.000000Z'
                    updated_at: '2023-08-25T06:30:08.000000Z'
                    roles:
                      - admin
                first_page_url: http://localhost:8000/api/v1/users?page=1
                from: 1
                last_page: 1
                last_page_url: http://localhost:8000/api/v1/users?page=1
                links:
                  - url: null
                    label: '&laquo; Previous'
                    active: false
                  - url: http://localhost:8000/api/v1/users?page=1
                    label: '1'
                    active: true
                  - url: null
                    label: Next &raquo;
                    active: false
                next_page_url: null
                path: http://localhost:8000/api/v1/users
                per_page: 20
                prev_page_url: null
                to: 4
                total: 4
    post:
      tags:
        - User
      summary: Create new
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: John
                last_name: Doe
                email: john.doed1@example.com
                password: secret
                roles:
                  - admin
                  - user
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:56:18 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '58'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  message: User created successfully
        '400':
          description: Bad Request
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:56:56 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '56'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Role users does not exist
                status: error
                code: 400
                data: null
        '422':
          description: Unprocessable Content
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:56:30 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '57'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Unprocessable Entity
                status: error
                code: 422
                data:
                  email:
                    - The email has already been taken.
  /users/1:
    get:
      tags:
        - User
      summary: Get one by Id
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:48:36 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '55'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  id: 1
                  email: admin@gmail.com
                  first_name: Admin
                  last_name: User
                  email_verified_at: null
                  created_at: '2023-08-25T06:25:42.000000Z'
                  updated_at: '2023-08-25T06:25:42.000000Z'
                  roles:
                    - admin
        '404':
          description: Not Found
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:48:11 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '57'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: User not found
                status: error
                code: 404
                data: null
  /users/3:
    delete:
      tags:
        - User
      summary: Delete by Id
      responses:
        '200':
          description: OK
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:56:03 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '59'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Request processed successfully
                status: success
                code: 200
                data:
                  message: User deleted successfully
        '404':
          description: Not Found
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:55:49 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '58'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: User not found
                status: error
                code: 404
                data: null
  /users/12:
    put:
      tags:
        - User
      summary: Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: John
                last_name: Doe
                email: john.doe1d@example.com
                password: secret
                roles:
                  - admin
                  - user
      responses:
        '404':
          description: Not Found
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:58:10 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '56'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: User not found
                status: error
                code: 404
                data: null
        '422':
          description: Unprocessable Content
          headers:
            Host:
              schema:
                type: string
                example: localhost:8000
            Date:
              schema:
                type: string
                example: Fri, 25 Aug 2023 13:57:41 GMT
            Connection:
              schema:
                type: string
                example: close
            X-Powered-By:
              schema:
                type: number
                example: PHP/8.2.1
            Cache-Control:
              schema:
                type: string
                example: no-cache, private
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RateLimit-Limit:
              schema:
                type: integer
                example: '60'
            X-RateLimit-Remaining:
              schema:
                type: integer
                example: '57'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                message: Unprocessable Entity
                status: error
                code: 422
                data:
                  email:
                    - The email has already been taken.
